version: "3.7"
services:
  application:
    image: application
    working_dir: /application
    command: "npm start"
    volumes:
      - ../config:/application/config
      - ../src:/application/src
      - ../package.json:/application/package.json
    depends_on:
      - "dynamodb"
    environment:
      - DYNAMODB_HOST=http://dynamodb:8000
      - USER_SERVICE_HOST=http://localhost
      - USER_SERVICE_PORT=3001
      - BORROWER_SERVICE_HOST=http://localhost
      - BORROWER_SERVICE_PORT=3002
      - APPLICATIOON_SERVICE_HOST=http://localhost:3000
    links:
      - dynamodb:dynamodb

  dynamodb:
    image: amazon/dynamodb-local
    ports:
      - "8000:8000"